import React from 'react';
import { pages } from './catalog.mjs';

const PALETTES = {
  ocean: { ink: '#17324D', primary: '#00467F', accent: '#0099CC', glow: '#8DD7E8', paper: '#EAF7FB', mist: '#F7FCFA', line: '#C7E1E6', warm: '#D6812B', muted: '#607482', positive: '#1C9853', danger: '#C0392B', caution: '#D6A21A' },
  spruce: { ink: '#183B35', primary: '#116B5D', accent: '#57AF7C', glow: '#A6DDD2', paper: '#F8FCFA', mist: '#E9F5F0', line: '#B9DDD0', warm: '#E9B64A', muted: '#627A72' },
  violet: { ink: '#292449', primary: '#5742A6', accent: '#8A67D7', glow: '#B5B5EE', paper: '#FAFAFE', mist: '#EFEFFC', line: '#CAC8EF', warm: '#E8B64B', muted: '#706D8D' },
};
const FONT = "'Microsoft YaHei','PingFang SC',Arial,sans-serif";
const c = key => PALETTES[key] || PALETTES.ocean;

function Root({ children, palette, dark = false, backgroundVariant, showRail, section, showBrand, brand, brandEn, showPage, page, total }) {
  const x = c(palette);
  const background = dark ? x.ink : backgroundVariant === 'paper' ? '#F7F5F0' : x.paper;
  return <section style={{ position: 'relative', width: 1920, height: 1080, overflow: 'hidden', fontFamily: FONT, background, color: dark ? '#fff' : x.ink }}>
    <CornerArt x={x} dark={dark} />
    {showRail && !dark && <LeftRail x={x} section={section} />}
    {showBrand !== false && <Brand x={x} dark={dark} name={brand} sub={brandEn} />}
    {children}
    <Footer x={x} dark={dark} show={showPage} page={page} total={total} />
  </section>;
}

function LeftRail({ x }) {
  return <div aria-hidden="true" style={{ position: 'absolute', left: 42, top: 88, bottom: 70, width: 2, background: x.line }}>
    <div style={{ position: 'absolute', top: 0, left: -5, width: 12, height: 12, borderRadius: '50%', background: x.primary }} />
    <div style={{ position: 'absolute', bottom: 0, left: -4, width: 10, height: 10, borderRadius: '50%', background: x.accent }} />
  </div>;
}

function CornerArt({ x, dark }) {
  return <div aria-hidden="true" style={{ position: 'absolute', right: -90, top: -105, width: 480, height: 480, opacity: dark ? .78 : .9 }}>
    <div style={{ position: 'absolute', inset: 0, border: `28px solid ${x.glow}`, borderRadius: '50%' }} />
    <div style={{ position: 'absolute', inset: 72, border: `20px solid ${x.accent}`, borderRadius: '50%' }} />
    <div style={{ position: 'absolute', inset: 154, background: x.warm, borderRadius: '50%' }} />
  </div>;
}

function Brand({ x, dark, name, sub }) {
  return <div style={{ position: 'absolute', left: 76, top: 54, display: 'flex', gap: 16, alignItems: 'center', color: dark ? '#fff' : x.ink }}>
    <div style={{ width: 54, height: 54, borderRadius: 14, background: x.primary, position: 'relative', overflow: 'hidden' }}><div style={{ position: 'absolute', width: 66, height: 12, left: -8, top: 21, background: x.warm, transform: 'rotate(-32deg)' }} /></div>
    <div><div style={{ fontSize: 26, fontWeight: 850, letterSpacing: 1.4 }}>{name}</div><div style={{ fontSize: 13, letterSpacing: 2.4, opacity: .7, marginTop: 3 }}>{sub}</div></div>
  </div>;
}

function Footer({ x, dark, show, page, total }) {
  return <><div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, height: 18, display: 'flex' }}><div style={{ flex: 5, background: x.primary }} /><div style={{ flex: 1.2, background: x.glow }} /><div style={{ flex: .7, background: x.accent }} /></div>{show !== false && <div style={{ position: 'absolute', right: 72, bottom: 40, fontSize: 17, fontWeight: 800, letterSpacing: 2, color: dark ? '#fff' : x.primary }}>{page} / {total}</div>}</>;
}

function Header({ x, kicker, title, section, wide = false }) {
  return <div style={{ position: 'absolute', left: 78, top: 148, width: wide ? 1620 : 1480 }}>{section && <div style={{ color: x.muted, fontSize: 14, fontWeight: 800, letterSpacing: 2, marginBottom: 14 }}>{section}</div>}<div style={{ color: x.accent, fontSize: 18, fontWeight: 850, letterSpacing: 4 }}>{kicker}</div><div style={{ marginTop: 22, fontSize: 58, lineHeight: 1.16, fontWeight: 800, letterSpacing: -2 }}>{title}</div></div>;
}
function Insight({ x, children }) { return <div style={{ position: 'absolute', left: 76, bottom: 58, width: 1510, minHeight: 46, padding: '12px 22px', borderLeft: `8px solid ${x.accent}`, background: x.mist, color: x.primary, fontSize: 18, lineHeight: 1.35, fontWeight: 700 }}>{children}</div>; }
const Cell = ({ x, children, dark = false, style = {} }) => <div style={{ background: dark ? x.primary : '#fff', color: dark ? '#fff' : x.ink, borderTop: `8px solid ${dark ? x.warm : x.accent}`, ...style }}>{children}</div>;

function Cover(props) { const x = c(props.palette); return <Root {...props}><div style={{ position: 'absolute', left: 94, top: 360, width: 1040 }}><div style={{ color: x.accent, fontSize: 20, fontWeight: 850, letterSpacing: 4 }}>{props.kicker}</div><div style={{ marginTop: 26, fontSize: 88, fontWeight: 850, letterSpacing: -5 }}>{props.title}</div><div style={{ marginTop: 28, width: 840, fontSize: 29, lineHeight: 1.45, color: x.muted }}>{props.subtitle}</div><div style={{ width: 118, height: 8, background: x.primary, marginTop: 72 }} /><div style={{ marginTop: 24, display: 'flex', gap: 38, fontSize: 20, color: x.muted }}><span>{props.owner}</span><span>{props.date}</span></div></div></Root>; }
function Agenda(props) { const x=c(props.palette), items=(props.items||[]).slice(0, props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{ position:'absolute',left:150,right:150,top:400,display:'grid',gridTemplateColumns:`repeat(${items.length},1fr)`,gap:30 }}>{items.map((v,i)=><Cell key={v} x={x} dark={i===0} style={{minHeight:300,padding:'38px'}}><div style={{fontSize:22,color:i===0?x.glow:x.accent,fontWeight:850}}>0{i+1}</div><div style={{fontSize:38,fontWeight:800,marginTop:78}}>{v}</div></Cell>)}</div></Root>; }
function Statement(props) { const x=c(props.palette); return <Root {...props} dark><div style={{position:'absolute',left:150,top:300,width:1320}}><div style={{fontSize:20,color:x.glow,letterSpacing:4,fontWeight:850}}>{props.kicker}</div><div style={{fontSize:76,lineHeight:1.17,fontWeight:850,marginTop:30}}>{props.title}</div><div style={{fontSize:30,lineHeight:1.5,color:'rgba(255,255,255,.72)',marginTop:38,width:980}}>{props.body}</div><div style={{marginTop:86,padding:'24px 32px',width:770,borderLeft:`8px solid ${x.warm}`,fontSize:28,fontWeight:750,color:x.glow}}>{props.quote}</div></div></Root>; }
function Cards(props) { const x=c(props.palette), items=(props.items||[]).slice(0,props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:78,right:78,top:405,display:'grid',gridTemplateColumns:`repeat(${items.length},1fr)`,gap:26}}>{items.map((v,i)=><Cell key={v.tag} x={x} dark={i===0} style={{minHeight:380,padding:'36px'}}><div style={{fontSize:18,fontWeight:850,color:i===0?x.glow:x.accent}}>{v.tag}</div><div style={{fontSize:36,fontWeight:850,marginTop:42}}>{v.title}</div><div style={{fontSize:22,lineHeight:1.55,marginTop:26,opacity:.75}}>{v.desc}</div></Cell>)}</div></Root>; }
function HeroMetric(props) { const x=c(props.palette), support=(props.supporting||[]).slice(0,props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:92,top:405,width:660}}><div style={{fontSize:118,fontWeight:900,color:x.primary,letterSpacing:-6}}>{props.value}<span style={{fontSize:34,marginLeft:14,letterSpacing:0}}>{props.unit}</span></div><div style={{fontSize:29,fontWeight:800,marginTop:26}}>{props.headline||props.body}</div><div style={{fontSize:20,lineHeight:1.6,color:x.muted,marginTop:20}}>{props.body}</div></div><div style={{position:'absolute',left:940,top:410,width:760,display:'grid',gap:16}}>{support.map((v,i)=><div key={v.label} style={{display:'grid',gridTemplateColumns:'150px 1fr',alignItems:'center',padding:'25px 30px',background:i===0?x.primary:x.mist,color:i===0?'#fff':x.ink}}><div style={{fontSize:34,fontWeight:850}}>{v.value}</div><div style={{fontSize:20,fontWeight:700}}>{v.label}</div></div>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }
function Trend(props) { const x=c(props.palette), series=props.series||[], max=Math.max(...series.map(v=>v.value),1); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:150,top:440,width:1120,height:360,borderLeft:`2px solid ${x.line}`,borderBottom:`2px solid ${x.line}`,display:'flex',alignItems:'end',gap:42,padding:'0 42px'}}>{series.map((v,i)=><div key={v.label} style={{flex:1,textAlign:'center'}}><div style={{fontSize:20,fontWeight:800,color:x.primary,marginBottom:12}}>{v.value}</div><div style={{height:`${Math.max(10,(v.value/max)*82)}%`,background:i===series.length-1?x.warm:x.accent,borderRadius:'10px 10px 0 0'}}/><div style={{marginTop:16,fontSize:18,color:x.muted}}>{v.label}</div></div>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }
function Comparison(props) { const x=c(props.palette); const Panel=({data,dark})=><Cell x={x} dark={dark} style={{padding:'38px 44px',minHeight:460}}><div style={{fontSize:38,fontWeight:850}}>{data.title}</div><div style={{fontSize:23,lineHeight:1.55,marginTop:24,opacity:.75}}>{data.desc}</div><div style={{marginTop:42,display:'grid',gap:16}}>{(data.points||[]).map((p,i)=><div key={p} style={{borderTop:`1px solid ${dark?'rgba(255,255,255,.25)':x.line}`,paddingTop:15,fontSize:22}}>{String(i+1).padStart(2,'0')}　{p}</div>)}</div></Cell>; return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:92,right:92,top:405,display:'grid',gridTemplateColumns:'1fr 1fr',gap:32}}><Panel data={props.left} /><Panel data={props.right} dark /></div><Insight x={x}>{props.insight}</Insight></Root>; }
function Metrics(props) { const x=c(props.palette), items=(props.metrics||[]).slice(0,props.itemCount||4); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:82,right:82,top:430,display:'grid',gridTemplateColumns:`repeat(${items.length},1fr)`,gap:20}}>{items.map((v,i)=><Cell key={v.label} x={x} dark={i===0} style={{padding:'34px',minHeight:315}}><div style={{fontSize:62,fontWeight:900,color:i===0?'#fff':x.primary}}>{v.value}</div><div style={{marginTop:50,fontSize:25,fontWeight:800}}>{v.label}</div><div style={{marginTop:16,color:i===0?x.glow:x.accent,fontSize:18,fontWeight:800}}>{v.delta}</div></Cell>)}</div></Root>; }
function Overview(props) { const x=c(props.palette), items=(props.items||[]).slice(0,props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:100,right:100,top:420,display:'grid',gridTemplateColumns:`repeat(${items.length},1fr)`,gap:28}}>{items.map((v,i)=><Cell key={v.no} x={x} dark={i===1} style={{padding:'30px 34px',minHeight:350}}><div style={{color:i===1?x.glow:x.accent,fontSize:20,fontWeight:850}}>{v.no}</div><div style={{marginTop:28,fontSize:34,fontWeight:850}}>{v.title}</div><div style={{marginTop:25,fontSize:23,lineHeight:1.5,opacity:.76}}>{v.desc}</div><div style={{marginTop:52,fontSize:40,fontWeight:900,color:i===1?x.warm:x.primary}}>{v.value}</div></Cell>)}</div></Root>; }
function Steps(props) { const x=c(props.palette), steps=(props.steps||props.phases||[]).slice(0,props.itemCount||4); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:110,right:110,top:450,display:'flex',alignItems:'stretch'}}>{steps.map((v,i)=><React.Fragment key={v.no}><Cell x={x} dark={i===0} style={{flex:1,padding:'28px',minHeight:280}}><div style={{fontSize:22,fontWeight:850,color:i===0?x.glow:x.accent}}>{v.no}</div><div style={{fontSize:30,fontWeight:850,marginTop:36}}>{v.title}</div><div style={{fontSize:19,lineHeight:1.5,marginTop:18,opacity:.75}}>{v.desc}</div></Cell>{i<steps.length-1&&<div style={{width:38,display:'grid',placeItems:'center',fontSize:30,color:x.accent}}>→</div>}</React.Fragment>)}</div></Root>; }
function Projects(props) { const x=c(props.palette), items=(props.projects||[]).slice(0,props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:92,right:92,top:410,display:'grid',gap:20}}>{items.map((v,i)=><div key={v.title} style={{display:'grid',gridTemplateColumns:'140px 1fr 170px 150px',gap:28,alignItems:'center',padding:'26px 30px',background:i===0?x.primary:x.mist,color:i===0?'#fff':x.ink}}><div style={{fontWeight:850,color:i===0?x.glow:x.accent}}>{v.status}</div><div><div style={{fontSize:29,fontWeight:850}}>{v.title}</div><div style={{height:10,background:i===0?'rgba(255,255,255,.2)':x.line,marginTop:16}}><div style={{height:'100%',width:`${v.progress}%`,background:i===0?x.warm:x.accent}}/></div></div><div style={{fontSize:19}}>{v.owner}</div><div style={{fontWeight:800}}>{v.date}</div></div>)}</div></Root>; }
function Narrative(props) { const x=c(props.palette); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:150,top:430,width:1120,fontSize:28,lineHeight:1.65,color:x.muted}}>{props.body}</div><div style={{position:'absolute',left:150,top:650,width:940,padding:'30px 38px',background:x.primary,color:'#fff',fontSize:26,fontWeight:750,borderLeft:`10px solid ${x.warm}`}}>{props.callout}</div></Root>; }
function Risks(props) { const x=c(props.palette), items=(props.items||[]).slice(0,props.itemCount||3), tone=v=>v.level==='高'?{bg:'#FFEEEF',mark:x.danger,label:'高风险'}:v.level==='中'?{bg:'#FFF8E1',mark:x.caution,label:'需关注'}:{bg:'#E8F5E9',mark:x.positive,label:'可控'}; return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:92,right:92,top:420,display:'grid',gap:18}}>{items.map(v=>{const t=tone(v); return <div key={v.title} style={{display:'grid',gridTemplateColumns:'142px 340px 220px 1fr',gap:26,alignItems:'center',padding:'26px 34px',background:t.bg,color:x.ink,borderLeft:`12px solid ${t.mark}`}}><div style={{fontWeight:900,color:t.mark}}><span style={{display:'inline-block',width:10,height:10,borderRadius:'50%',background:t.mark,marginRight:10}}/>{t.label}</div><div style={{fontSize:29,fontWeight:850}}>{v.title}</div><div>{v.owner}</div><div style={{fontSize:20,fontWeight:700}}>{v.action}</div></div>})}</div><Insight x={x}>{props.insight||'风险色阶只表达优先级，需同步给出责任人与控制动作。'}</Insight></Root>; }
function Closing(props) { const x=c(props.palette); return <Root {...props} dark><div style={{position:'absolute',left:150,top:360,width:1180}}><div style={{fontSize:20,color:x.glow,fontWeight:850,letterSpacing:4}}>{props.kicker}</div><div style={{fontSize:78,fontWeight:850,marginTop:26}}>{props.title}</div><div style={{fontSize:30,color:'rgba(255,255,255,.72)',marginTop:32}}>{props.subtitle}</div><div style={{marginTop:84,fontSize:20,color:x.glow}}>{props.contact}</div></div></Root>; }
function ExecutiveSummary(props) { return <Cards {...props} />; }
function DataSpotlight(props) { return <HeroMetric {...props} />; }
function Matrix(props) { const x=c(props.palette), rows=(props.rows||[]).slice(0,props.itemCount||4); return <Root {...props}><Header x={x} {...props} wide/><div style={{position:'absolute',left:76,right:76,top:365}}><div style={{display:'grid',gridTemplateColumns:'260px 1fr 1fr 1fr',padding:'22px 28px',background:x.primary,color:'#fff',fontSize:20,fontWeight:850}}><div>决策维度</div><div>{props.leftTitle}</div><div>{props.rightTitle}</div><div style={{color:x.glow}}>{props.recommended}</div></div>{rows.map((v,i)=><div key={v.dimension} style={{display:'grid',gridTemplateColumns:'260px 1fr 1fr 1fr',padding:'26px 28px',background:i%2?x.mist:'#fff',borderBottom:`1px solid ${x.line}`,fontSize:20}}><div style={{fontWeight:850,color:x.primary}}>{v.dimension}</div><div>{v.left}</div><div>{v.right}</div><div style={{fontWeight:850,color:x.accent}}>{v.verdict}</div></div>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }
function Diagnosis(props) { const x=c(props.palette), layers=props.layers||[]; return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:110,right:110,top:365,display:'grid',gap:20}}>{layers.map((v,i)=><div key={v.level} style={{display:'grid',gridTemplateColumns:'150px 370px 1fr 270px',gap:24,alignItems:'center',padding:'28px 34px',background:i===2?x.primary:(i===1?x.mist:'#fff'),color:i===2?'#fff':x.ink,border:`1px solid ${i===2?x.primary:x.line}`}}><div style={{fontWeight:850,color:i===2?x.glow:x.accent}}>{v.level}</div><div style={{fontSize:30,fontWeight:850}}>{v.title}</div><div style={{fontSize:20,opacity:.78}}>{v.desc}</div><div style={{fontWeight:850,color:i===2?x.warm:x.accent}}>{v.signal}</div></div>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }
function Architecture(props) { const x=c(props.palette), layers=(props.layers||[]).slice(0,props.itemCount||4); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:170,right:170,top:390,display:'grid',gap:16}}>{layers.map((v,i)=><div key={v.no} style={{display:'grid',gridTemplateColumns:'100px 330px 1fr 180px',gap:26,alignItems:'center',padding:'21px 30px',background:i===1?x.primary:(i%2?x.mist:'#fff'),color:i===1?'#fff':x.ink,borderLeft:`12px solid ${[x.accent,x.warm,x.glow,x.primary][i]}`}}><div style={{fontSize:28,fontWeight:900,color:i===1?x.glow:x.accent}}>{v.no}</div><div style={{fontSize:29,fontWeight:850}}>{v.title}</div><div style={{fontSize:20,opacity:.78}}>{v.desc}</div><div style={{fontWeight:850,color:i===1?x.warm:x.accent}}>{v.tag}</div></div>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }
function Governance(props) { const x=c(props.palette), actors=(props.actors||[]).slice(0,props.itemCount||4), pos=[{left:82,top:400},{left:82,top:660},{right:82,top:400},{right:82,top:660}]; return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:690,top:470,width:540,height:220,background:x.primary,color:'#fff',borderRadius:36,display:'grid',placeItems:'center',textAlign:'center',padding:30}}><div><div style={{fontSize:40,fontWeight:850}}>{props.center?.title}</div><div style={{marginTop:14,color:x.glow,fontSize:19}}>{props.center?.subtitle}</div></div></div>{actors.map((v,i)=><div key={v.title} style={{position:'absolute',...pos[i],width:420,padding:'24px 28px',background:i===0?x.mist:'#fff',borderTop:`8px solid ${[x.accent,x.warm,x.glow,x.primary][i]}`}}><div style={{fontSize:27,fontWeight:850}}>{v.title}</div><div style={{marginTop:12,fontSize:19,color:x.muted}}>{v.scope}</div><div style={{marginTop:14,fontSize:18,color:x.primary,fontWeight:750}}>{v.rule}</div></div>)}<Insight x={x}>{props.insight}</Insight></Root>; }
function Roadmap(props) { const x=c(props.palette), phases=(props.phases||[]).slice(0,props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:100,right:100,top:385,display:'grid',gridTemplateColumns:`repeat(${phases.length},1fr)`,gap:24}}>{phases.map((v,i)=><Cell key={v.no} x={x} dark={i===0} style={{minHeight:445,padding:'30px'}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{fontSize:34,fontWeight:900,color:i===0?x.glow:x.accent}}>{v.no}</div><div style={{fontSize:17,opacity:.7}}>{v.period}</div></div><div style={{marginTop:26,fontSize:31,fontWeight:850}}>{v.title}</div><div style={{marginTop:22,fontSize:20,lineHeight:1.5}}>{v.objective}</div><div style={{height:1,background:i===0?'rgba(255,255,255,.25)':x.line,margin:'26px 0'}}/><div style={{fontSize:18,opacity:.68}}>关键动作</div><div style={{fontSize:18,lineHeight:1.5,marginTop:10}}>{v.actions}</div><div style={{display:'inline-block',padding:'8px 12px',background:i===0?x.warm:'#fff',color:i===0?x.ink:x.primary,fontWeight:850,marginTop:24}}>{v.result}</div></Cell>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }
function Actions(props) { const x=c(props.palette), items=(props.items||[]).slice(0,props.itemCount||3); return <Root {...props}><Header x={x} {...props}/><div style={{position:'absolute',left:92,right:92,top:400,display:'grid',gridTemplateColumns:`repeat(${items.length},1fr)`,gap:24}}>{items.map((v,i)=><Cell key={v.title} x={x} dark={i===0} style={{padding:'32px',minHeight:400}}><div style={{display:'grid',placeItems:'center',width:70,height:70,background:i===0?x.warm:x.glow,color:x.ink,fontSize:24,fontWeight:900}}>{v.priority}</div><div style={{fontSize:33,fontWeight:850,marginTop:32}}>{v.title}</div><div style={{fontSize:20,lineHeight:1.55,marginTop:20,opacity:.78}}>{v.desc}</div><div style={{height:1,background:i===0?'rgba(255,255,255,.25)':x.line,margin:'28px 0 18px'}}/><div style={{display:'flex',justifyContent:'space-between',fontSize:18}}><span>{v.owner}</span><span style={{fontWeight:850,color:i===0?x.warm:x.accent}}>{v.timing}</span></div></Cell>)}</div><Insight x={x}>{props.insight}</Insight></Root>; }

const components = [Cover, Agenda, Statement, Cards, HeroMetric, Trend, Comparison, Metrics, Overview, Steps, Comparison, Steps, Projects, Narrative, Risks, Closing, ExecutiveSummary, DataSpotlight, Matrix, Diagnosis, Architecture, Governance, Roadmap, Actions];
export const runtimePages = pages.map((entry, index) => ({ ...entry, Component: components[index], controls: entry.controls, defaultProps: entry.defaultProps, meta: { key: entry.slot, label: entry.label } }));
