const swissBase = {
  '--paper': '#fafaf8',
  '--paper-rgb': '250,250,248',
  '--ink': '#0a0a0a',
  '--ink-rgb': '10,10,10',
  '--grey-1': '#f0f0ee',
  '--grey-2': '#d4d4d2',
  '--grey-3': '#737373',
};

function theme(label, vars, roles = {}) {
  const palette = { ...swissBase, ...vars };
  return {
    label,
    vars: {
      ...palette,
      '--paper-tint': palette['--grey-1'],
      '--surface-bg': palette['--paper'],
      '--surface-rgb': palette['--paper-rgb'],
      '--surface-fg': palette['--ink'],
      '--inverse-bg': palette['--ink'],
      '--inverse-rgb': palette['--ink-rgb'],
      '--inverse-fg': palette['--paper'],
      '--text-primary': palette['--ink'],
      '--text-secondary': 'color-mix(in srgb, var(--ink) 72%, var(--paper))',
      '--text-helper': palette['--grey-3'],
      '--text-placeholder': 'color-mix(in srgb, var(--ink) 38%, var(--paper))',
      '--text-on-color': palette['--accent-on'],
      '--border-subtle': palette['--grey-2'],
      '--border-strong': palette['--grey-3'],
      '--focus-bg': palette['--accent'],
      '--focus-rgb': palette['--accent-rgb'],
      '--focus-fg': palette['--accent-on'],
      '--focus-muted': 'color-mix(in srgb, var(--focus-fg) 72%, transparent)',
      '--focus-mark': palette['--accent'],
      ...roles,
    },
  };
}

export const THEME_OPTIONS = {
  ikb: theme('克莱因蓝 IKB', {
    '--accent': '#002FA7',
    '--accent-rgb': '0,47,167',
    '--accent-on': '#ffffff',
    '--accent-bright': '#5B7BFF',
  }),
  lemon: theme('柠檬黄', {
    '--accent': '#FFD500',
    '--accent-rgb': '255,213,0',
    '--accent-on': '#0a0a0a',
    '--accent-bright': '#FFD500',
  }, {
    '--focus-mark': '#8a6f00',
  }),
  green: theme('柠檬绿', {
    '--accent': '#C5E803',
    '--accent-rgb': '197,232,3',
    '--accent-on': '#0a0a0a',
    '--accent-bright': '#C5E803',
  }, {
    '--focus-mark': '#587000',
  }),
  orange: theme('安全橙', {
    '--accent': '#FF6B35',
    '--accent-rgb': '255,107,53',
    '--accent-on': '#ffffff',
    '--accent-bright': '#FF6B35',
  }, {
    '--focus-mark': '#c84412',
  }),
  monocle: theme('墨水经典', {
    '--paper': '#f1efea',
    '--paper-rgb': '241,239,234',
    '--ink': '#0a0a0b',
    '--ink-rgb': '10,10,11',
    '--grey-1': '#e8e5de',
    '--grey-2': '#d6d1c7',
    '--grey-3': '#716b63',
    '--accent': '#0a0a0b',
    '--accent-rgb': '10,10,11',
    '--accent-on': '#f1efea',
    '--accent-bright': '#18181a',
    '--ink-tint': '#18181a',
  }),
  indigo: theme('靛蓝瓷', {
    '--paper': '#f1f3f5',
    '--paper-rgb': '241,243,245',
    '--ink': '#0a1f3d',
    '--ink-rgb': '10,31,61',
    '--grey-1': '#e4e8ec',
    '--grey-2': '#cdd5dd',
    '--grey-3': '#607086',
    '--accent': '#0a1f3d',
    '--accent-rgb': '10,31,61',
    '--accent-on': '#f1f3f5',
    '--accent-bright': '#2f5f98',
    '--ink-tint': '#152a4a',
  }),
  forest: theme('森林墨', {
    '--paper': '#f5f1e8',
    '--paper-rgb': '245,241,232',
    '--ink': '#1a2e1f',
    '--ink-rgb': '26,46,31',
    '--grey-1': '#ece7da',
    '--grey-2': '#d7cfbd',
    '--grey-3': '#687263',
    '--accent': '#1a2e1f',
    '--accent-rgb': '26,46,31',
    '--accent-on': '#f5f1e8',
    '--accent-bright': '#426c4c',
    '--ink-tint': '#253d2c',
  }),
  kraft: theme('牛皮纸', {
    '--paper': '#eedfc7',
    '--paper-rgb': '238,223,199',
    '--ink': '#2a1e13',
    '--ink-rgb': '42,30,19',
    '--grey-1': '#e0d0b6',
    '--grey-2': '#cbb998',
    '--grey-3': '#736552',
    '--accent': '#2a1e13',
    '--accent-rgb': '42,30,19',
    '--accent-on': '#eedfc7',
    '--accent-bright': '#6b4b31',
    '--ink-tint': '#3a2a1d',
  }),
  dune: theme('沙丘', {
    '--paper': '#f0e6d2',
    '--paper-rgb': '240,230,210',
    '--ink': '#1f1a14',
    '--ink-rgb': '31,26,20',
    '--grey-1': '#e3d7bf',
    '--grey-2': '#cec1aa',
    '--grey-3': '#6d665b',
    '--accent': '#1f1a14',
    '--accent-rgb': '31,26,20',
    '--accent-on': '#f0e6d2',
    '--accent-bright': '#63523f',
    '--ink-tint': '#2d2620',
  }),
};

export const DEFAULT_THEME = 'ikb';
