import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { buildSync } from 'esbuild';
import {
  LAYOUT_ALIASES,
  LAYOUT_OPTIONS,
  DEFAULT_THEME_PACK,
  THEME_PACK_OPTIONS,
  resolveOption,
} from './options.jsx';
import {
  buildDeckViewModel,
  renderDeckView,
  serializeDeckViewModel,
} from './view-model/index.jsx';

const ROOT = path.resolve(import.meta.dirname, '..');
const MIGRATION_ONLY_DIRS = new Set(['uploads', 'screens', 'screenshots', 'shots', 'scratch']);

export function renderDeck(deck, { outFile, includeThemeSwitcher = deck.preview?.themeSwitcher === true }) {
  const viewModel = buildDeckViewModel(deck, {
    layouts: LAYOUT_OPTIONS,
    layoutAliases: LAYOUT_ALIASES,
    themePacks: THEME_PACK_OPTIONS,
    defaultThemePack: DEFAULT_THEME_PACK,
    resolveOption,
  });
  const { key: themePackName } = viewModel.themePack;
  const template = fs.readFileSync(path.join(ROOT, 'assets/template-swiss.html'), 'utf8');
  const slides = renderToStaticMarkup(<>{renderDeckView(viewModel)}</>);
  let html = insertSlides(template, slides);
  html = html.replace('<html lang="zh-CN">', `<html lang="zh-CN" data-theme-pack="${themePackName}">`);
  html = html.replace('<title>[必填] 替换为 PPT 标题 · Deck Title</title>', `<title>${escapeHtml(viewModel.model.title)}</title>`);
  html = injectPreviewOptions(html, viewModel.options, { includeThemeSwitcher });
  html = injectDeckViewModel(html, serializeDeckViewModel(viewModel));
  html = html.replace('<link rel="preconnect" href="https://fonts.googleapis.com">', '<link rel="icon" href="data:,">\n<link rel="preconnect" href="https://fonts.googleapis.com">');

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, html);
  copyRuntimeAssets(path.dirname(outFile));
}

function insertSlides(template, slides) {
  const startMatch = template.match(/<div id="deck"[^>]*>/);
  const startTag = startMatch?.[0];
  const start = startMatch?.index ?? -1;
  const nav = template.indexOf('<div id="nav"', start);
  const deckEnd = findClosingDiv(template, start);

  if (start === -1 || nav === -1 || deckEnd === -1) {
    throw new Error('Template is missing <div id="deck"> or <div id="nav"> markers.');
  }

  const before = template.slice(0, start + startTag.length);
  const after = template.slice(deckEnd);
  return `${before}\n\n<!-- Generated by scripts/render-deck.jsx -->\n${slides}\n\n${after}`;
}

function findClosingDiv(html, start) {
  if (start < 0) return -1;
  const tagPattern = /<\/?div\b[^>]*>/gi;
  tagPattern.lastIndex = start;
  let depth = 0;
  let match;
  while ((match = tagPattern.exec(html))) {
    if (match[0].startsWith('</')) {
      depth -= 1;
      if (depth === 0) return match.index;
    } else {
      depth += 1;
    }
  }
  return -1;
}

function injectPreviewOptions(html, options, { includeThemeSwitcher = false } = {}) {
  const previewOptions = {
    ...options,
    themePacks: includeThemeSwitcher ? options.themePacks : {},
  };
  const json = escapeScriptJson(JSON.stringify(previewOptions));
  return html.replace(
    /<script id="preview-options" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="preview-options" type="application/json">${json}</script>`,
  );
}

function injectDeckViewModel(html, viewModel) {
  const json = escapeScriptJson(JSON.stringify(viewModel));
  return html.replace(
    /<script id="deck-view-model" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="deck-view-model" type="application/json">${json}</script>`,
  );
}

function copyRuntimeAssets(outDir) {
  const assetsDir = path.join(outDir, 'assets');
  const imagesDir = path.join(outDir, 'images');
  [assetsDir, imagesDir, path.join(outDir, 'uploads'), path.join(outDir, 'screens'), path.join(outDir, 'screenshots')].forEach(dir => {
    fs.rmSync(dir, { recursive: true, force: true });
  });
  fs.mkdirSync(assetsDir, { recursive: true });
  copyFileIfExists(path.join(ROOT, 'node_modules/gsap/dist/gsap.min.js'), path.join(assetsDir, 'vendor/gsap.min.js'));
  copyFileIfExists(path.join(ROOT, 'node_modules/pptxgenjs/dist/pptxgen.bundle.js'), path.join(assetsDir, 'vendor/pptxgen.bundle.js'));
  copyFileIfExists(path.join(ROOT, 'node_modules/html-to-image/dist/html-to-image.js'), path.join(assetsDir, 'vendor/html-to-image.js'));
  copyImportedThemeAssets(outDir);
  buildImportedThemeRuntime(path.join(assetsDir, 'imported-theme-runtime.js'));
  const imageSlotStateFile = path.join(outDir, '.image-slots.state.json');
  if (!fs.existsSync(imageSlotStateFile)) fs.writeFileSync(imageSlotStateFile, '{}\n');
}

function buildImportedThemeRuntime(outFile) {
  buildSync({
    entryPoints: [path.join(ROOT, 'src/components/themes/client-runtime.jsx')],
    outfile: outFile,
    bundle: true,
    format: 'iife',
    globalName: 'DeckJsxRuntime',
    platform: 'browser',
    jsx: 'automatic',
    loader: {
      '.css': 'text',
    },
    inject: [path.join(ROOT, 'src/react-shim.js')],
    define: {
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'silent',
  });
}

function copyImportedThemeAssets(outDir) {
  const themesDir = path.join(ROOT, 'src/components/themes');
  if (!fs.existsSync(themesDir)) return;
  for (const themeKey of fs.readdirSync(themesDir)) {
    const sourceDir = path.join(themesDir, themeKey, 'source');
    if (!fs.existsSync(sourceDir)) continue;
    const files = [];
    collectThemeAssetFiles(sourceDir, files);
    files.forEach(from => {
      const rel = path.relative(sourceDir, from);
      const to = path.join(outDir, rel);
      fs.mkdirSync(path.dirname(to), { recursive: true });
      fs.copyFileSync(from, to);
    });
  }
}

function collectThemeAssetFiles(dir, out) {
  for (const name of fs.readdirSync(dir)) {
    const file = path.join(dir, name);
    const stat = fs.statSync(file);
    if (stat.isDirectory()) {
      if (MIGRATION_ONLY_DIRS.has(name.toLowerCase())) continue;
      collectThemeAssetFiles(file, out);
      continue;
    }
    if (/\.(png|jpe?g|webp|gif|svg|mp4|mov)$/i.test(name)) out.push(file);
  }
}

function copyFileIfExists(from, to) {
  if (fs.existsSync(from)) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeScriptJson(value) {
  return value
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}
