import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  DEFAULT_FONT,
  DEFAULT_SPACING,
  DEFAULT_THEME,
  DEFAULT_TYPE_SCALE,
  FONT_OPTIONS,
  SPACING_OPTIONS,
  THEME_OPTIONS,
  TYPE_SCALE_OPTIONS,
  resolveOption,
} from './options.jsx';

const ROOT = path.resolve(import.meta.dirname, '..');

export function renderDeck(deck, { outFile }) {
  if (deck.style && deck.style !== 'swiss') {
    throw new Error('Only style "swiss" is supported by the component workflow.');
  }

  const { key: themeName, option: theme } = resolveOption(THEME_OPTIONS, deck.theme, DEFAULT_THEME, 'theme');
  const { key: fontName, option: font } = resolveOption(FONT_OPTIONS, deck.fontSet, DEFAULT_FONT, 'fontSet');
  const { key: typeScaleName, option: typeScale } = resolveOption(TYPE_SCALE_OPTIONS, deck.typeScale, DEFAULT_TYPE_SCALE, 'typeScale');
  const { key: spacingName, option: spacing } = resolveOption(SPACING_OPTIONS, deck.spacing, DEFAULT_SPACING, 'spacing');
  const template = fs.readFileSync(path.join(ROOT, 'assets/template-swiss.html'), 'utf8');
  const slides = renderToStaticMarkup(<>{React.Children.toArray(deck.slides)}</>);
  let html = insertSlides(template, slides);
  html = html.replace('<title>[必填] 替换为 PPT 标题 · Deck Title</title>', `<title>${escapeHtml(deck.title)}</title>`);
  html = replaceCssVars(html, { ...theme.vars, ...font.vars, ...typeScale.vars, ...spacing.vars });
  html = replaceOptionLabels(html, { themeLabel: theme.label, fontLabel: font.label, fontName });
  html = injectPreviewOptions(html, {
    themes: serializeOptions(THEME_OPTIONS),
    fonts: serializeOptions(FONT_OPTIONS),
    typeScales: serializeOptions(TYPE_SCALE_OPTIONS),
    spacings: serializeOptions(SPACING_OPTIONS),
    current: {
      theme: themeName,
      font: fontName,
      typeScale: typeScaleName,
      spacing: spacingName,
    },
  });
  html = html.replace('<link rel="preconnect" href="https://fonts.googleapis.com">', '<link rel="icon" href="data:,">\n<link rel="preconnect" href="https://fonts.googleapis.com">');

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, html);
  copyRuntimeAssets(path.dirname(outFile));
}

function replaceOptionLabels(html, { themeLabel, fontLabel, fontName }) {
  return html
    .replace(/主题色\(默认:\s*[^)]+\)/, `主题色(当前: ${themeLabel})`)
    .replace(/\/\*\s*高亮色:\s*[^*]+\*\//, `/* 高亮色: ${themeLabel} */`)
    .replace(/\/\*\s*=+\s*字体\(跨主题固定\)\s*=+\s*\*\//, `/* ============ 字体(当前: ${fontName} · ${fontLabel}) ============ */`);
}

function insertSlides(template, slides) {
  const startTag = '<div id="deck">';
  const start = template.indexOf(startTag);
  const nav = template.indexOf('<div id="nav"', start);
  const deckEnd = template.lastIndexOf('</div>', nav);

  if (start === -1 || nav === -1 || deckEnd === -1) {
    throw new Error('Template is missing <div id="deck"> or <div id="nav"> markers.');
  }

  const before = template.slice(0, start + startTag.length);
  const after = template.slice(deckEnd);
  return `${before}\n\n<!-- Generated by scripts/render-deck.jsx -->\n${slides}\n\n${after}`;
}

function replaceCssVars(html, vars) {
  let next = html;
  for (const [name, value] of Object.entries(vars)) {
    next = next.replace(new RegExp(`(${escapeRegExp(name)}\\s*:\\s*)[^;]+;`, 'g'), `$1${value};`);
  }
  return next;
}

function serializeOptions(registry) {
  return Object.fromEntries(
    Object.entries(registry).map(([key, option]) => [
      key,
      {
        label: option.label,
        vars: option.vars,
        classes: option.classes,
        dataAnimate: option.dataAnimate,
      },
    ]),
  );
}

function injectPreviewOptions(html, options) {
  const json = escapeScriptJson(JSON.stringify(options));
  return html.replace(
    /<script id="preview-options" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="preview-options" type="application/json">${json}</script>`,
  );
}

function copyRuntimeAssets(outDir) {
  const assetsDir = path.join(outDir, 'assets');
  const imagesDir = path.join(outDir, 'images');
  fs.mkdirSync(assetsDir, { recursive: true });
  fs.mkdirSync(imagesDir, { recursive: true });
  fs.copyFileSync(path.join(ROOT, 'assets/motion.min.js'), path.join(assetsDir, 'motion.min.js'));
  copyDirectoryIfExists(path.join(ROOT, 'assets/screenshot-backgrounds'), path.join(assetsDir, 'screenshot-backgrounds'));

  const placeholder = path.join(imagesDir, 'placeholder-21x9.svg');
  if (!fs.existsSync(placeholder)) {
    fs.writeFileSync(placeholder, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2100 900">
  <rect width="2100" height="900" fill="#f0f0ee"/>
  <path d="M0 700H2100M340 0V900M1760 0V900" stroke="#d4d4d2" stroke-width="3"/>
  <rect x="690" y="250" width="720" height="260" fill="#fafaf8"/>
  <text x="1050" y="405" text-anchor="middle" font-family="Arial, sans-serif" font-size="72" fill="#737373">21:9 IMAGE SLOT</text>
</svg>`);
  }
}

function copyDirectoryIfExists(from, to) {
  if (fs.existsSync(from)) {
    fs.cpSync(from, to, { recursive: true });
  }
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeScriptJson(value) {
  return value
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}
